# Generated by Django 2.2.10 on 2020-05-17 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='standardpage',
            name='page_subtitle',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
