# Generated by Django 3.0.6 on 2020-06-14 21:40

from django.db import migrations, models
import django.db.models.deletion
import taxonomy.models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
        ('wagtailimages', '0001_squashed_0021'),
        ('pages', '0002_auto_20200517_0116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=80)),
                ('last_name', models.CharField(max_length=80)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(default='', limit_choices_to=taxonomy.models.Node.get_department_categories, on_delete=django.db.models.deletion.PROTECT, to='taxonomy.Node')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image')),
            ],
            options={
                'verbose_name': 'person',
                'verbose_name_plural': 'people',
            },
        ),
    ]
