# Generated by Django 3.0.6 on 2020-06-14 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_peopleindexpage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peopleindexpage',
            name='people',
        ),
    ]
