# Generated by Django 3.0.6 on 2020-06-14 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_remove_peopleindexpage_people'),
    ]

    operations = [
        migrations.AddField(
            model_name='peopleindexpage',
            name='page_subtitle',
            field=models.TextField(blank=True, max_length=255),
        ),
    ]
